let all_product = [
  {
    id: 1,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p1_product_i1.png',
    new_price: 50.0,
    old_price: 80.5,
  },
  {
    id: 2,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p2_product_i2.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 3,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p3_product_i3.png',
    new_price: 60.0,
    old_price: 100.5,
  },
  {
    id: 4,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p4_product_i4.png',
    new_price: 100.0,
    old_price: 150.0,
  },
  {
    id: 5,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p5_product_i5.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 6,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p6_product_i6.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 7,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p7_product_i7.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 8,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p8_product_i8.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 9,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p9_product_i9.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 10,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p10_product_i10.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 11,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p11_product_i11.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 12,
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'women',
    image: 'assets/p12_product_i12.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 13,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p13_product_i13.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 14,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p14_product_i14.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 15,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p15_product_i15.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 16,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p16_product_i16.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 17,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p17_product_i17.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 18,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p18_product_i18.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 19,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p19_product_i19.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 20,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p20_product_i20.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 21,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p21_product_i21.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 22,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p22_product_i22.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 23,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p23_product_i23.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 24,
    name: 'Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket',
    category: 'men',
    image: 'assets/p24_product_i24.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 25,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p25_product_i25.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 26,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p26_product_i26.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 27,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p27_product_i27.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 28,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p28_product_i28.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 29,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p29_product_i29.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 30,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p30_product_i30.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 31,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p31_product_i31.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 32,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p32_product_i32.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 33,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p33_product_i33.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 34,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p34_product_i34.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 35,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p35_product_i35.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 36,
    name: 'Boys Orange Colourblocked Hooded Sweatshirt',
    category: 'kid',
    image: 'assets/p36_product_i36.png',
    new_price: 85.0,
    old_price: 120.5,
  },
];

export default all_product;
